
def get_property_setters():
    property_setters = [
        {
            "doc_type": "Supplier",
            "default_value": None,
            "docstatus": 0,
            "doctype_or_field": "DocType",
            "doctype": "Property Setter",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:44:35.768322",
            "module": "Akwad ERPNext Fixes",
            "name": "Supplier-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Customer",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-02-29 15:52:18.474494",
            "module": "Akwad ERPNext Fixes",
            "name": "Customer-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Serial No",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-02-29 15:52:32.482600",
            "module": "Akwad ERPNext Fixes",
            "name": "Serial No-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Journal Entry",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:46:09.086455",
            "module": "Akwad ERPNext Fixes",
            "name": "Journal Entry-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Salary Structure Assignment",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:46:25.880113",
            "module": "Akwad ERPNext Fixes",
            "name": "Salary Structure Assignment-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Payment Entry",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:46:42.722278",
            "module": "Akwad ERPNext Fixes",
            "name": "Payment Entry-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Stock Entry",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:46:57.740250",
            "module": "Akwad ERPNext Fixes",
            "name": "Stock Entry-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Employee Checkin",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:47:16.282261",
            "module": "Akwad ERPNext Fixes",
            "name": "Employee Checkin-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Purchase Invoice",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:48:05.590159",
            "module": "Akwad ERPNext Fixes",
            "name": "Purchase Invoice-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Sales Invoice",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:48:12.571001",
            "module": "Akwad ERPNext Fixes",
            "name": "Sales Invoice-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Sales Order",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:48:59.033927",
            "module": "Akwad ERPNext Fixes",
            "name": "Sales Order-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Purchase Order",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:49:07.533752",
            "module": "Akwad ERPNext Fixes",
            "name": "Purchase Order-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "POS Invoice",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:52:09.564345",
            "module": "Akwad ERPNext Fixes",
            "name": "POS Invoice-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        }
    ]

    return property_setters
